- hosts: all

  tasks:

   - name: Generate hosts file
     lineinfile: dest=/etc/hosts
                 regexp='.*{{ item }}$'
                 line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
                 state=present
     when: hostvars[item].ansible_default_ipv4.address is defined
     with_items: "{{groups['all']}}"
     become: true

   #- name: Set hostname
   #  hostname: name="{{inventory_hostname}}"
   #  become: true

   - name: apt update
     apt: update_cache=yes upgrade=dist
     become: true

   - name: Download git repository
     become: true
     git:
      repo: 'https://github.com/sztoor/model_serving.git'
      dest: /model_serving

   - name: Change ownership of a directory
     become: true
     file:
      path: /technical-training
      state: directory
      recurse: yes
      owner: appuser
      group: appuser

- hosts: node_training

  tasks:
   - name: Install pip
     apt: pkg=python3-pip state=latest update_cache=true
     become: true

   - name: Install ML packages
     become: true
     pip:
      name: tensorflow==2.10.0, keras==2.10.0, numpy, future, ray["default"], ray["air"], tensorflow_addons, tensorf>

    - name: Join Ray cluster
      become: true
      shell: ray start --address='192.168.2.145:6379'
